spring:
  application:
    name: redis-e2e-monitoring

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      username: null
      password: null
      timeout: 500ms
      ssl:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

  metrics:
    tags:
      application: ${spring.application.name}
      cluster: ${app.redis.cluster-name}
    distribution:
      percentiles:
        redis_e2e_write_milliseconds: 0.5, 0.75, 0.95, 0.99
        redis_e2e_read_milliseconds: 0.5, 0.75, 0.95, 0.99
        redis_e2e_delete_milliseconds: 0.5, 0.75, 0.95, 0.99
      percentiles-histogram:
        redis_e2e_write_milliseconds: true
        redis_e2e_read_milliseconds: true
        redis_e2e_delete_milliseconds: true

  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        enabled: false
        step: 30s

app:
  redis:
    cluster-name: unknown-cluster
    probe-interval: 1s
    probe-ttl: 60s
    metrics:
      delay: 10s
      min-bucket-bound: 1ms
      max-bucket-bound: 50ms