version: 2.1

workflows:
  gitops_pipeline:
    jobs:
      - build_and_test:
          context: gcp-context

      - push_image_to_gar:
          context: gcp-context
          requires:
            - build_and_test
          filters:
            branches:
              only: main

      - deploy_to_argo:
          context: gcp-context
          requires:
            - push_image_to_gar
          filters:
            branches:
              only: main

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - setup_remote_docker
      - gradle/with_cache:
          cache_key: build-v1
          deps_checksum_file: gradle.properties
          steps:
            - run:
                name: Export version
                command: |
                  VERSION=$(gradle properties -q | grep "^version:" | awk '{print $2}')
                  echo "$VERSION" > version
            - run:
                name: Assemble the code
                command: gradle build
      - gradle/collect_test_results
      - persist_to_workspace:
          root: .
          paths:
            - build
            - version

  push_image_to_gar:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - install_gcloud
      - authenticate_gcloud
      - configure_docker_provider
      - run:
          name: Build and Push Docker Image
          command: |
            APP_VERSION=$(cat version)
            GAR_IMAGE="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/my-java-repo/java-app:${APP_VERSION}"

            ./gradlew bootBuildImage --imageName=$GAR_IMAGE
            docker push $GAR_IMAGE

  deploy_to_argo:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Clone Argo repo
          command: |
            REPO_DIR="$HOME/argo-repo"
            echo "export REPO_DIR=$REPO_DIR" >> $BASH_ENV

            git clone --depth=1 \
              --branch main \
              --config "user.name=argo-cd[bot]" \
              --config "user.email=argo-cd[bot]@users.noreply.github.com" \
              "https://x-access-token:${ARGOCD_REPOSITORY_ACCESS_TOKEN}@${ARGOCD_REPOSITORY_URL}" \
              "$REPO_DIR"

      - run:
          name: Update image tag
          command: |
            APP_VERSION=$(cat /tmp/workspace/version)
            yq -i ".image.tag = \"${APP_VERSION}\"" ${REPO_DIR}/charts/redis-monitoring/values.yaml
            git -C ${REPO_DIR} diff

      - run:
          name: Commit and push
          command: |
            APP_VERSION=$(cat /tmp/workspace/version)
            git -C ${REPO_DIR} commit -am "chore: bump redis-service to ${APP_VERSION} [skip ci]"
            git -C ${REPO_DIR} push

commands:
  install_gcloud:
    description: "Download and install Google Cloud SDK CLI"
    steps:
      - run:
          name: Install Google Cloud CLI
          command: |
            curl -sSL https://sdk.cloud.google.com -o install.sh
            bash install.sh --disable-prompts > /dev/null
            echo "export PATH=$PATH:$HOME/google-cloud-sdk/bin" >> $BASH_ENV

  authenticate_gcloud:
    description: "Exchange CircleCI OIDC token for temporary GCP access"
    steps:
      - run:
          name: Authenticate via OIDC Workload Identity
          command: |
            echo "$CIRCLE_OIDC_TOKEN" > /tmp/gcp_oidc_token.txt

            gcloud iam workload-identity-pools create-cred-config \
                "projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/circleci-pool-v4/providers/circleci-provider" \
                --output-file=/tmp/gcp_cred_config.json \
                --service-account="circleci-uploader@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
                --credential-source-file=/tmp/gcp_oidc_token.txt

            echo "export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_cred_config.json" >> $BASH_ENV

            gcloud auth login --cred-file=/tmp/gcp_cred_config.json --quiet
            gcloud config set project ${GCP_PROJECT_ID} --quiet

  configure_docker_provider:
    description: "Configuring the Docker daemon to work with Artifact Registry"
    steps:
      - run:
          name: Configure Docker Auth
          command: gcloud auth configure-docker "${GCP_REGION}-docker.pkg.dev" --quiet